// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/storage/v1alpha/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatasetState int32

const (
	DatasetState_DATASET_STATE_UNSPECIFIED DatasetState = 0
	DatasetState_DATASET_STATE_UPLOADING   DatasetState = 1
	DatasetState_DATASET_STATE_READY       DatasetState = 2
	DatasetState_DATASET_STATE_REMOVED     DatasetState = 3
)

// Enum value maps for DatasetState.
var (
	DatasetState_name = map[int32]string{
		0: "DATASET_STATE_UNSPECIFIED",
		1: "DATASET_STATE_UPLOADING",
		2: "DATASET_STATE_READY",
		3: "DATASET_STATE_REMOVED",
	}
	DatasetState_value = map[string]int32{
		"DATASET_STATE_UNSPECIFIED": 0,
		"DATASET_STATE_UPLOADING":   1,
		"DATASET_STATE_READY":       2,
		"DATASET_STATE_REMOVED":     3,
	}
)

func (x DatasetState) Enum() *DatasetState {
	p := new(DatasetState)
	*p = x
	return p
}

func (x DatasetState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatasetState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_storage_v1alpha_storage_proto_enumTypes[0].Descriptor()
}

func (DatasetState) Type() protoreflect.EnumType {
	return &file_proto_storage_v1alpha_storage_proto_enumTypes[0]
}

func (x DatasetState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DatasetState.Descriptor instead.
func (DatasetState) EnumDescriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{0}
}

type ReserveDatasetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetName   string                 `protobuf:"bytes,1,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty" validate:"required,lte=128"` // @gotags: validate:"required,lte=128"
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty" validate:"required,min=1,max=8192,dive,required,lte=1024"`                                // @gotags: validate:"required,min=1,max=8192,dive,required,lte=1024"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveDatasetRequest) Reset() {
	*x = ReserveDatasetRequest{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveDatasetRequest) ProtoMessage() {}

func (x *ReserveDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveDatasetRequest.ProtoReflect.Descriptor instead.
func (*ReserveDatasetRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveDatasetRequest) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *ReserveDatasetRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type UploadTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty" validate:"required,url"` // @gotags: validate:"required,url"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTarget) Reset() {
	*x = UploadTarget{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTarget) ProtoMessage() {}

func (x *UploadTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTarget.ProtoReflect.Descriptor instead.
func (*UploadTarget) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{1}
}

func (x *UploadTarget) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadTarget) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

type ReserveDatasetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uploads       []*UploadTarget        `protobuf:"bytes,1,rep,name=uploads,proto3" json:"uploads,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	DatasetId     string                 `protobuf:"bytes,3,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty" validate:"required,len=32"`       // @gotags: validate:"required,len=32"
	DatasetName   string                 `protobuf:"bytes,4,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty" validate:"required,lte=128"` // @gotags: validate:"required,lte=128"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveDatasetResponse) Reset() {
	*x = ReserveDatasetResponse{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveDatasetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveDatasetResponse) ProtoMessage() {}

func (x *ReserveDatasetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveDatasetResponse.ProtoReflect.Descriptor instead.
func (*ReserveDatasetResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveDatasetResponse) GetUploads() []*UploadTarget {
	if x != nil {
		return x.Uploads
	}
	return nil
}

func (x *ReserveDatasetResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ReserveDatasetResponse) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *ReserveDatasetResponse) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

type CommitDatasetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty" validate:"required,len=32"` // @gotags: validate:"required,len=32"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitDatasetRequest) Reset() {
	*x = CommitDatasetRequest{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitDatasetRequest) ProtoMessage() {}

func (x *CommitDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitDatasetRequest.ProtoReflect.Descriptor instead.
func (*CommitDatasetRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{3}
}

func (x *CommitDatasetRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

type CommitDatasetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitDatasetResponse) Reset() {
	*x = CommitDatasetResponse{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitDatasetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitDatasetResponse) ProtoMessage() {}

func (x *CommitDatasetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitDatasetResponse.ProtoReflect.Descriptor instead.
func (*CommitDatasetResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{4}
}

type DeleteDatasetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty" validate:"required,len=32"` // @gotags: validate:"required,len=32"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatasetRequest) Reset() {
	*x = DeleteDatasetRequest{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatasetRequest) ProtoMessage() {}

func (x *DeleteDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatasetRequest.ProtoReflect.Descriptor instead.
func (*DeleteDatasetRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDatasetRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

type DeleteDatasetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatasetResponse) Reset() {
	*x = DeleteDatasetResponse{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatasetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatasetResponse) ProtoMessage() {}

func (x *DeleteDatasetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatasetResponse.ProtoReflect.Descriptor instead.
func (*DeleteDatasetResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{6}
}

type ListDatasetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty" validate:"omitempty,lte=128"`                        // @gotags: validate:"omitempty,lte=128"
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty" validate:"omitempty,gte=1,lte=512"`   // @gotags: validate:"omitempty,gte=1,lte=512"
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty" validate:"omitempty,lte=8191"`                       // @gotags: validate:"omitempty,lte=8191"
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty" validate:"omitempty,lte=1024"` // @gotags: validate:"omitempty,lte=1024"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsRequest) Reset() {
	*x = ListDatasetsRequest{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsRequest) ProtoMessage() {}

func (x *ListDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsRequest.ProtoReflect.Descriptor instead.
func (*ListDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{7}
}

func (x *ListDatasetsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListDatasetsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDatasetsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListDatasetsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListDatasetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasets      []*DatasetSummary      `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsResponse) Reset() {
	*x = ListDatasetsResponse{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsResponse) ProtoMessage() {}

func (x *ListDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsResponse.ProtoReflect.Descriptor instead.
func (*ListDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{8}
}

func (x *ListDatasetsResponse) GetDatasets() []*DatasetSummary {
	if x != nil {
		return x.Datasets
	}
	return nil
}

func (x *ListDatasetsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type DatasetSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	DatasetName   string                 `protobuf:"bytes,2,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	State         DatasetState           `protobuf:"varint,3,opt,name=state,proto3,enum=olcf.s3m.storage.v1alpha.DatasetState" json:"state,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ContentLength int64                  `protobuf:"varint,6,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetSummary) Reset() {
	*x = DatasetSummary{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetSummary) ProtoMessage() {}

func (x *DatasetSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetSummary.ProtoReflect.Descriptor instead.
func (*DatasetSummary) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{9}
}

func (x *DatasetSummary) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *DatasetSummary) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *DatasetSummary) GetState() DatasetState {
	if x != nil {
		return x.State
	}
	return DatasetState_DATASET_STATE_UNSPECIFIED
}

func (x *DatasetSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DatasetSummary) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *DatasetSummary) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

type DatasetSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Selector:
	//
	//	*DatasetSelector_DatasetId
	//	*DatasetSelector_DatasetName
	Selector      isDatasetSelector_Selector `protobuf_oneof:"selector"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetSelector) Reset() {
	*x = DatasetSelector{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetSelector) ProtoMessage() {}

func (x *DatasetSelector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetSelector.ProtoReflect.Descriptor instead.
func (*DatasetSelector) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{10}
}

func (x *DatasetSelector) GetSelector() isDatasetSelector_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *DatasetSelector) GetDatasetId() string {
	if x != nil {
		if x, ok := x.Selector.(*DatasetSelector_DatasetId); ok {
			return x.DatasetId
		}
	}
	return ""
}

func (x *DatasetSelector) GetDatasetName() *DatasetNameSelector {
	if x != nil {
		if x, ok := x.Selector.(*DatasetSelector_DatasetName); ok {
			return x.DatasetName
		}
	}
	return nil
}

type isDatasetSelector_Selector interface {
	isDatasetSelector_Selector()
}

type DatasetSelector_DatasetId struct {
	DatasetId string `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3,oneof" validate:"required,len=32"` // @gotags: validate:"required,len=32"
}

type DatasetSelector_DatasetName struct {
	DatasetName *DatasetNameSelector `protobuf:"bytes,2,opt,name=dataset_name,json=datasetName,proto3,oneof" validate:"required"` // @gotags: validate:"required"
}

func (*DatasetSelector_DatasetId) isDatasetSelector_Selector() {}

func (*DatasetSelector_DatasetName) isDatasetSelector_Selector() {}

type DatasetNameSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"required,lte=128"` // @gotags: validate:"required,lte=128"
	Latest        bool                   `protobuf:"varint,2,opt,name=latest,proto3" json:"latest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetNameSelector) Reset() {
	*x = DatasetNameSelector{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetNameSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetNameSelector) ProtoMessage() {}

func (x *DatasetNameSelector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetNameSelector.ProtoReflect.Descriptor instead.
func (*DatasetNameSelector) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{11}
}

func (x *DatasetNameSelector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DatasetNameSelector) GetLatest() bool {
	if x != nil {
		return x.Latest
	}
	return false
}

type GetDatasetContentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *DatasetSelector       `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty" validate:"required"`                          // @gotags: validate:"required"
	PathPrefix    string                 `protobuf:"bytes,2,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty" validate:"omitempty,lte=1024"`    // @gotags: validate:"omitempty,lte=1024"
	GlobPattern   string                 `protobuf:"bytes,3,opt,name=glob_pattern,json=globPattern,proto3" json:"glob_pattern,omitempty" validate:"omitempty,lte=1024"` // @gotags: validate:"omitempty,lte=1024"
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty" validate:"omitempty,gte=1,lte=512"`         // @gotags: validate:"omitempty,gte=1,lte=512"
	Offset        uint32                 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty" validate:"omitempty,lte=8191"`                             // @gotags: validate:"omitempty,lte=8191"
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty" validate:"omitempty,lte=1024"`       // @gotags: validate:"omitempty,lte=1024"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatasetContentsRequest) Reset() {
	*x = GetDatasetContentsRequest{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasetContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasetContentsRequest) ProtoMessage() {}

func (x *GetDatasetContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasetContentsRequest.ProtoReflect.Descriptor instead.
func (*GetDatasetContentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{12}
}

func (x *GetDatasetContentsRequest) GetSelector() *DatasetSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *GetDatasetContentsRequest) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *GetDatasetContentsRequest) GetGlobPattern() string {
	if x != nil {
		return x.GlobPattern
	}
	return ""
}

func (x *GetDatasetContentsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetDatasetContentsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetDatasetContentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetDatasetContentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileEntry           `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatasetContentsResponse) Reset() {
	*x = GetDatasetContentsResponse{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasetContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasetContentsResponse) ProtoMessage() {}

func (x *GetDatasetContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasetContentsResponse.ProtoReflect.Descriptor instead.
func (*GetDatasetContentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{13}
}

func (x *GetDatasetContentsResponse) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GetDatasetContentsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	LastModified  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{14}
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

type GetDownloadURLsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Selector *DatasetSelector       `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty" validate:"required"` // @gotags: validate:"required"
	// Types that are valid to be assigned to PathFilter:
	//
	//	*GetDownloadURLsRequest_Paths
	//	*GetDownloadURLsRequest_GlobPattern
	PathFilter    isGetDownloadURLsRequest_PathFilter `protobuf_oneof:"path_filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLsRequest) Reset() {
	*x = GetDownloadURLsRequest{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLsRequest) ProtoMessage() {}

func (x *GetDownloadURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLsRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{15}
}

func (x *GetDownloadURLsRequest) GetSelector() *DatasetSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *GetDownloadURLsRequest) GetPathFilter() isGetDownloadURLsRequest_PathFilter {
	if x != nil {
		return x.PathFilter
	}
	return nil
}

func (x *GetDownloadURLsRequest) GetPaths() *PathList {
	if x != nil {
		if x, ok := x.PathFilter.(*GetDownloadURLsRequest_Paths); ok {
			return x.Paths
		}
	}
	return nil
}

func (x *GetDownloadURLsRequest) GetGlobPattern() string {
	if x != nil {
		if x, ok := x.PathFilter.(*GetDownloadURLsRequest_GlobPattern); ok {
			return x.GlobPattern
		}
	}
	return ""
}

type isGetDownloadURLsRequest_PathFilter interface {
	isGetDownloadURLsRequest_PathFilter()
}

type GetDownloadURLsRequest_Paths struct {
	Paths *PathList `protobuf:"bytes,2,opt,name=paths,proto3,oneof"`
}

type GetDownloadURLsRequest_GlobPattern struct {
	GlobPattern string `protobuf:"bytes,3,opt,name=glob_pattern,json=globPattern,proto3,oneof" validate:"required,lte=1024"` // @gotags: validate:"required,lte=1024"
}

func (*GetDownloadURLsRequest_Paths) isGetDownloadURLsRequest_PathFilter() {}

func (*GetDownloadURLsRequest_GlobPattern) isGetDownloadURLsRequest_PathFilter() {}

type PathList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty" validate:"required,min=1,max=8192,dive,required,lte=1024"` // @gotags: validate:"required,min=1,max=8192,dive,required,lte=1024"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathList) Reset() {
	*x = PathList{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathList) ProtoMessage() {}

func (x *PathList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathList.ProtoReflect.Descriptor instead.
func (*PathList) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{16}
}

func (x *PathList) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type DownloadTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty" validate:"required,url"` // @gotags: validate:"required,url"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTarget) Reset() {
	*x = DownloadTarget{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTarget) ProtoMessage() {}

func (x *DownloadTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTarget.ProtoReflect.Descriptor instead.
func (*DownloadTarget) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{17}
}

func (x *DownloadTarget) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DownloadTarget) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type GetDownloadURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Downloads     []*DownloadTarget      `protobuf:"bytes,1,rep,name=downloads,proto3" json:"downloads,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLsResponse) Reset() {
	*x = GetDownloadURLsResponse{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLsResponse) ProtoMessage() {}

func (x *GetDownloadURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLsResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{18}
}

func (x *GetDownloadURLsResponse) GetDownloads() []*DownloadTarget {
	if x != nil {
		return x.Downloads
	}
	return nil
}

func (x *GetDownloadURLsResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextOffset    uint32                 `protobuf:"varint,1,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_v1alpha_storage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_proto_storage_v1alpha_storage_proto_rawDescGZIP(), []int{19}
}

func (x *Pagination) GetNextOffset() uint32 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

func (x *Pagination) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *Pagination) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_proto_storage_v1alpha_storage_proto protoreflect.FileDescriptor

const file_proto_storage_v1alpha_storage_proto_rawDesc = "" +
	"\n" +
	"#proto/storage/v1alpha/storage.proto\x12\x18olcf.s3m.storage.v1alpha\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n" +
	"\x15ReserveDatasetRequest\x12!\n" +
	"\fdataset_name\x18\x01 \x01(\tR\vdatasetName\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\"A\n" +
	"\fUploadTarget\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\"\xd7\x01\n" +
	"\x16ReserveDatasetResponse\x12@\n" +
	"\auploads\x18\x01 \x03(\v2&.olcf.s3m.storage.v1alpha.UploadTargetR\auploads\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x03 \x01(\tR\tdatasetId\x12!\n" +
	"\fdataset_name\x18\x04 \x01(\tR\vdatasetName\"5\n" +
	"\x14CommitDatasetRequest\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\"\x17\n" +
	"\x15CommitDatasetResponse\"5\n" +
	"\x14DeleteDatasetRequest\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\"\x17\n" +
	"\x15DeleteDatasetResponse\"\x81\x01\n" +
	"\x13ListDatasetsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xa2\x01\n" +
	"\x14ListDatasetsResponse\x12D\n" +
	"\bdatasets\x18\x01 \x03(\v2(.olcf.s3m.storage.v1alpha.DatasetSummaryR\bdatasets\x12D\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2$.olcf.s3m.storage.v1alpha.PaginationR\n" +
	"pagination\"\xad\x02\n" +
	"\x0eDatasetSummary\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\x12!\n" +
	"\fdataset_name\x18\x02 \x01(\tR\vdatasetName\x12<\n" +
	"\x05state\x18\x03 \x01(\x0e2&.olcf.s3m.storage.v1alpha.DatasetStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12%\n" +
	"\x0econtent_length\x18\x06 \x01(\x03R\rcontentLength\"\x92\x01\n" +
	"\x0fDatasetSelector\x12\x1f\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tH\x00R\tdatasetId\x12R\n" +
	"\fdataset_name\x18\x02 \x01(\v2-.olcf.s3m.storage.v1alpha.DatasetNameSelectorH\x00R\vdatasetNameB\n" +
	"\n" +
	"\bselector\"A\n" +
	"\x13DatasetNameSelector\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06latest\x18\x02 \x01(\bR\x06latest\"\xfa\x01\n" +
	"\x19GetDatasetContentsRequest\x12E\n" +
	"\bselector\x18\x01 \x01(\v2).olcf.s3m.storage.v1alpha.DatasetSelectorR\bselector\x12\x1f\n" +
	"\vpath_prefix\x18\x02 \x01(\tR\n" +
	"pathPrefix\x12!\n" +
	"\fglob_pattern\x18\x03 \x01(\tR\vglobPattern\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\rR\x06offset\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"\x9d\x01\n" +
	"\x1aGetDatasetContentsResponse\x129\n" +
	"\x05files\x18\x01 \x03(\v2#.olcf.s3m.storage.v1alpha.FileEntryR\x05files\x12D\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2$.olcf.s3m.storage.v1alpha.PaginationR\n" +
	"pagination\"t\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12?\n" +
	"\rlast_modified\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified\"\xcf\x01\n" +
	"\x16GetDownloadURLsRequest\x12E\n" +
	"\bselector\x18\x01 \x01(\v2).olcf.s3m.storage.v1alpha.DatasetSelectorR\bselector\x12:\n" +
	"\x05paths\x18\x02 \x01(\v2\".olcf.s3m.storage.v1alpha.PathListH\x00R\x05paths\x12#\n" +
	"\fglob_pattern\x18\x03 \x01(\tH\x00R\vglobPatternB\r\n" +
	"\vpath_filter\" \n" +
	"\bPathList\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"G\n" +
	"\x0eDownloadTarget\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\"\x9c\x01\n" +
	"\x17GetDownloadURLsResponse\x12F\n" +
	"\tdownloads\x18\x01 \x03(\v2(.olcf.s3m.storage.v1alpha.DownloadTargetR\tdownloads\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"p\n" +
	"\n" +
	"Pagination\x12\x1f\n" +
	"\vnext_offset\x18\x01 \x01(\rR\n" +
	"nextOffset\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken*~\n" +
	"\fDatasetState\x12\x1d\n" +
	"\x19DATASET_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DATASET_STATE_UPLOADING\x10\x01\x12\x17\n" +
	"\x13DATASET_STATE_READY\x10\x02\x12\x19\n" +
	"\x15DATASET_STATE_REMOVED\x10\x032\xd0\x05\n" +
	"\rBucketGateway\x12s\n" +
	"\x0eReserveDataset\x12/.olcf.s3m.storage.v1alpha.ReserveDatasetRequest\x1a0.olcf.s3m.storage.v1alpha.ReserveDatasetResponse\x12p\n" +
	"\rCommitDataset\x12..olcf.s3m.storage.v1alpha.CommitDatasetRequest\x1a/.olcf.s3m.storage.v1alpha.CommitDatasetResponse\x12p\n" +
	"\rDeleteDataset\x12..olcf.s3m.storage.v1alpha.DeleteDatasetRequest\x1a/.olcf.s3m.storage.v1alpha.DeleteDatasetResponse\x12m\n" +
	"\fListDatasets\x12-.olcf.s3m.storage.v1alpha.ListDatasetsRequest\x1a..olcf.s3m.storage.v1alpha.ListDatasetsResponse\x12\x7f\n" +
	"\x12GetDatasetContents\x123.olcf.s3m.storage.v1alpha.GetDatasetContentsRequest\x1a4.olcf.s3m.storage.v1alpha.GetDatasetContentsResponse\x12v\n" +
	"\x0fGetDownloadURLs\x120.olcf.s3m.storage.v1alpha.GetDownloadURLsRequest\x1a1.olcf.s3m.storage.v1alpha.GetDownloadURLsResponseB4Z2github.com/olcf/s3m-apis/storage/v1alpha;storagepbb\x06proto3"

var (
	file_proto_storage_v1alpha_storage_proto_rawDescOnce sync.Once
	file_proto_storage_v1alpha_storage_proto_rawDescData []byte
)

func file_proto_storage_v1alpha_storage_proto_rawDescGZIP() []byte {
	file_proto_storage_v1alpha_storage_proto_rawDescOnce.Do(func() {
		file_proto_storage_v1alpha_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_v1alpha_storage_proto_rawDesc), len(file_proto_storage_v1alpha_storage_proto_rawDesc)))
	})
	return file_proto_storage_v1alpha_storage_proto_rawDescData
}

var file_proto_storage_v1alpha_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_storage_v1alpha_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_storage_v1alpha_storage_proto_goTypes = []any{
	(DatasetState)(0),                  // 0: olcf.s3m.storage.v1alpha.DatasetState
	(*ReserveDatasetRequest)(nil),      // 1: olcf.s3m.storage.v1alpha.ReserveDatasetRequest
	(*UploadTarget)(nil),               // 2: olcf.s3m.storage.v1alpha.UploadTarget
	(*ReserveDatasetResponse)(nil),     // 3: olcf.s3m.storage.v1alpha.ReserveDatasetResponse
	(*CommitDatasetRequest)(nil),       // 4: olcf.s3m.storage.v1alpha.CommitDatasetRequest
	(*CommitDatasetResponse)(nil),      // 5: olcf.s3m.storage.v1alpha.CommitDatasetResponse
	(*DeleteDatasetRequest)(nil),       // 6: olcf.s3m.storage.v1alpha.DeleteDatasetRequest
	(*DeleteDatasetResponse)(nil),      // 7: olcf.s3m.storage.v1alpha.DeleteDatasetResponse
	(*ListDatasetsRequest)(nil),        // 8: olcf.s3m.storage.v1alpha.ListDatasetsRequest
	(*ListDatasetsResponse)(nil),       // 9: olcf.s3m.storage.v1alpha.ListDatasetsResponse
	(*DatasetSummary)(nil),             // 10: olcf.s3m.storage.v1alpha.DatasetSummary
	(*DatasetSelector)(nil),            // 11: olcf.s3m.storage.v1alpha.DatasetSelector
	(*DatasetNameSelector)(nil),        // 12: olcf.s3m.storage.v1alpha.DatasetNameSelector
	(*GetDatasetContentsRequest)(nil),  // 13: olcf.s3m.storage.v1alpha.GetDatasetContentsRequest
	(*GetDatasetContentsResponse)(nil), // 14: olcf.s3m.storage.v1alpha.GetDatasetContentsResponse
	(*FileEntry)(nil),                  // 15: olcf.s3m.storage.v1alpha.FileEntry
	(*GetDownloadURLsRequest)(nil),     // 16: olcf.s3m.storage.v1alpha.GetDownloadURLsRequest
	(*PathList)(nil),                   // 17: olcf.s3m.storage.v1alpha.PathList
	(*DownloadTarget)(nil),             // 18: olcf.s3m.storage.v1alpha.DownloadTarget
	(*GetDownloadURLsResponse)(nil),    // 19: olcf.s3m.storage.v1alpha.GetDownloadURLsResponse
	(*Pagination)(nil),                 // 20: olcf.s3m.storage.v1alpha.Pagination
	(*timestamppb.Timestamp)(nil),      // 21: google.protobuf.Timestamp
}
var file_proto_storage_v1alpha_storage_proto_depIdxs = []int32{
	2,  // 0: olcf.s3m.storage.v1alpha.ReserveDatasetResponse.uploads:type_name -> olcf.s3m.storage.v1alpha.UploadTarget
	21, // 1: olcf.s3m.storage.v1alpha.ReserveDatasetResponse.expires_at:type_name -> google.protobuf.Timestamp
	10, // 2: olcf.s3m.storage.v1alpha.ListDatasetsResponse.datasets:type_name -> olcf.s3m.storage.v1alpha.DatasetSummary
	20, // 3: olcf.s3m.storage.v1alpha.ListDatasetsResponse.pagination:type_name -> olcf.s3m.storage.v1alpha.Pagination
	0,  // 4: olcf.s3m.storage.v1alpha.DatasetSummary.state:type_name -> olcf.s3m.storage.v1alpha.DatasetState
	21, // 5: olcf.s3m.storage.v1alpha.DatasetSummary.created_at:type_name -> google.protobuf.Timestamp
	21, // 6: olcf.s3m.storage.v1alpha.DatasetSummary.expires_at:type_name -> google.protobuf.Timestamp
	12, // 7: olcf.s3m.storage.v1alpha.DatasetSelector.dataset_name:type_name -> olcf.s3m.storage.v1alpha.DatasetNameSelector
	11, // 8: olcf.s3m.storage.v1alpha.GetDatasetContentsRequest.selector:type_name -> olcf.s3m.storage.v1alpha.DatasetSelector
	15, // 9: olcf.s3m.storage.v1alpha.GetDatasetContentsResponse.files:type_name -> olcf.s3m.storage.v1alpha.FileEntry
	20, // 10: olcf.s3m.storage.v1alpha.GetDatasetContentsResponse.pagination:type_name -> olcf.s3m.storage.v1alpha.Pagination
	21, // 11: olcf.s3m.storage.v1alpha.FileEntry.last_modified:type_name -> google.protobuf.Timestamp
	11, // 12: olcf.s3m.storage.v1alpha.GetDownloadURLsRequest.selector:type_name -> olcf.s3m.storage.v1alpha.DatasetSelector
	17, // 13: olcf.s3m.storage.v1alpha.GetDownloadURLsRequest.paths:type_name -> olcf.s3m.storage.v1alpha.PathList
	18, // 14: olcf.s3m.storage.v1alpha.GetDownloadURLsResponse.downloads:type_name -> olcf.s3m.storage.v1alpha.DownloadTarget
	21, // 15: olcf.s3m.storage.v1alpha.GetDownloadURLsResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 16: olcf.s3m.storage.v1alpha.BucketGateway.ReserveDataset:input_type -> olcf.s3m.storage.v1alpha.ReserveDatasetRequest
	4,  // 17: olcf.s3m.storage.v1alpha.BucketGateway.CommitDataset:input_type -> olcf.s3m.storage.v1alpha.CommitDatasetRequest
	6,  // 18: olcf.s3m.storage.v1alpha.BucketGateway.DeleteDataset:input_type -> olcf.s3m.storage.v1alpha.DeleteDatasetRequest
	8,  // 19: olcf.s3m.storage.v1alpha.BucketGateway.ListDatasets:input_type -> olcf.s3m.storage.v1alpha.ListDatasetsRequest
	13, // 20: olcf.s3m.storage.v1alpha.BucketGateway.GetDatasetContents:input_type -> olcf.s3m.storage.v1alpha.GetDatasetContentsRequest
	16, // 21: olcf.s3m.storage.v1alpha.BucketGateway.GetDownloadURLs:input_type -> olcf.s3m.storage.v1alpha.GetDownloadURLsRequest
	3,  // 22: olcf.s3m.storage.v1alpha.BucketGateway.ReserveDataset:output_type -> olcf.s3m.storage.v1alpha.ReserveDatasetResponse
	5,  // 23: olcf.s3m.storage.v1alpha.BucketGateway.CommitDataset:output_type -> olcf.s3m.storage.v1alpha.CommitDatasetResponse
	7,  // 24: olcf.s3m.storage.v1alpha.BucketGateway.DeleteDataset:output_type -> olcf.s3m.storage.v1alpha.DeleteDatasetResponse
	9,  // 25: olcf.s3m.storage.v1alpha.BucketGateway.ListDatasets:output_type -> olcf.s3m.storage.v1alpha.ListDatasetsResponse
	14, // 26: olcf.s3m.storage.v1alpha.BucketGateway.GetDatasetContents:output_type -> olcf.s3m.storage.v1alpha.GetDatasetContentsResponse
	19, // 27: olcf.s3m.storage.v1alpha.BucketGateway.GetDownloadURLs:output_type -> olcf.s3m.storage.v1alpha.GetDownloadURLsResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_storage_v1alpha_storage_proto_init() }
func file_proto_storage_v1alpha_storage_proto_init() {
	if File_proto_storage_v1alpha_storage_proto != nil {
		return
	}
	file_proto_storage_v1alpha_storage_proto_msgTypes[10].OneofWrappers = []any{
		(*DatasetSelector_DatasetId)(nil),
		(*DatasetSelector_DatasetName)(nil),
	}
	file_proto_storage_v1alpha_storage_proto_msgTypes[15].OneofWrappers = []any{
		(*GetDownloadURLsRequest_Paths)(nil),
		(*GetDownloadURLsRequest_GlobPattern)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_v1alpha_storage_proto_rawDesc), len(file_proto_storage_v1alpha_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_storage_v1alpha_storage_proto_goTypes,
		DependencyIndexes: file_proto_storage_v1alpha_storage_proto_depIdxs,
		EnumInfos:         file_proto_storage_v1alpha_storage_proto_enumTypes,
		MessageInfos:      file_proto_storage_v1alpha_storage_proto_msgTypes,
	}.Build()
	File_proto_storage_v1alpha_storage_proto = out.File
	file_proto_storage_v1alpha_storage_proto_goTypes = nil
	file_proto_storage_v1alpha_storage_proto_depIdxs = nil
}
