// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/streaming/v1alpha/rabbitmq.proto

package streamingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RabbitMQClusterSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SyncStatus    string                 `protobuf:"bytes,3,opt,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty"`
	HealthStatus  string                 `protobuf:"bytes,4,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	Lifetime      *Lifetime              `protobuf:"bytes,5,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RabbitMQClusterSummary) Reset() {
	*x = RabbitMQClusterSummary{}
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RabbitMQClusterSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RabbitMQClusterSummary) ProtoMessage() {}

func (x *RabbitMQClusterSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RabbitMQClusterSummary.ProtoReflect.Descriptor instead.
func (*RabbitMQClusterSummary) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_rabbitmq_proto_rawDescGZIP(), []int{0}
}

func (x *RabbitMQClusterSummary) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RabbitMQClusterSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RabbitMQClusterSummary) GetSyncStatus() string {
	if x != nil {
		return x.SyncStatus
	}
	return ""
}

func (x *RabbitMQClusterSummary) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

func (x *RabbitMQClusterSummary) GetLifetime() *Lifetime {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

type RabbitMQCluster struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Kind             string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SyncStatus       string                 `protobuf:"bytes,3,opt,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty"`
	HealthStatus     string                 `protobuf:"bytes,4,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	Lifetime         *Lifetime              `protobuf:"bytes,5,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	ResourceSettings map[string]int32       `protobuf:"bytes,6,rep,name=resource_settings,json=resourceSettings,proto3" json:"resource_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Username         *string                `protobuf:"bytes,7,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password         *string                `protobuf:"bytes,8,opt,name=password,proto3,oneof" json:"password,omitempty"`
	AmqpsUrl         *string                `protobuf:"bytes,9,opt,name=amqps_url,json=amqpsUrl,proto3,oneof" json:"amqps_url,omitempty"`
	MgmtUrl          *string                `protobuf:"bytes,10,opt,name=mgmt_url,json=mgmtUrl,proto3,oneof" json:"mgmt_url,omitempty"`
	FeatureFlags     map[string]bool        `protobuf:"bytes,11,rep,name=feature_flags,json=featureFlags,proto3" json:"feature_flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RabbitMQCluster) Reset() {
	*x = RabbitMQCluster{}
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RabbitMQCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RabbitMQCluster) ProtoMessage() {}

func (x *RabbitMQCluster) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RabbitMQCluster.ProtoReflect.Descriptor instead.
func (*RabbitMQCluster) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_rabbitmq_proto_rawDescGZIP(), []int{1}
}

func (x *RabbitMQCluster) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RabbitMQCluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RabbitMQCluster) GetSyncStatus() string {
	if x != nil {
		return x.SyncStatus
	}
	return ""
}

func (x *RabbitMQCluster) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

func (x *RabbitMQCluster) GetLifetime() *Lifetime {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *RabbitMQCluster) GetResourceSettings() map[string]int32 {
	if x != nil {
		return x.ResourceSettings
	}
	return nil
}

func (x *RabbitMQCluster) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *RabbitMQCluster) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *RabbitMQCluster) GetAmqpsUrl() string {
	if x != nil && x.AmqpsUrl != nil {
		return *x.AmqpsUrl
	}
	return ""
}

func (x *RabbitMQCluster) GetMgmtUrl() string {
	if x != nil && x.MgmtUrl != nil {
		return *x.MgmtUrl
	}
	return ""
}

func (x *RabbitMQCluster) GetFeatureFlags() map[string]bool {
	if x != nil {
		return x.FeatureFlags
	}
	return nil
}

type ProvisionRabbitMQClusterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Kind             string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" validate:"required"`                                                                                                                            // @gotags: validate:"required"
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" validate:"required,max=40,hostname_rfc1123"`                                                                                                                            // @gotags: validate:"required,max=40,hostname_rfc1123"
	ResourceSettings map[string]int32       `protobuf:"bytes,3,rep,name=resource_settings,json=resourceSettings,proto3" json:"resource_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value" validate:"dive,keys,endkeys,gt=0"` // @gotags: validate:"dive,keys,endkeys,gt=0"
	FeatureFlags     map[string]bool        `protobuf:"bytes,4,rep,name=feature_flags,json=featureFlags,proto3" json:"feature_flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProvisionRabbitMQClusterRequest) Reset() {
	*x = ProvisionRabbitMQClusterRequest{}
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRabbitMQClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRabbitMQClusterRequest) ProtoMessage() {}

func (x *ProvisionRabbitMQClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRabbitMQClusterRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRabbitMQClusterRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_rabbitmq_proto_rawDescGZIP(), []int{2}
}

func (x *ProvisionRabbitMQClusterRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProvisionRabbitMQClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProvisionRabbitMQClusterRequest) GetResourceSettings() map[string]int32 {
	if x != nil {
		return x.ResourceSettings
	}
	return nil
}

func (x *ProvisionRabbitMQClusterRequest) GetFeatureFlags() map[string]bool {
	if x != nil {
		return x.FeatureFlags
	}
	return nil
}

type ProvisionRabbitMQClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	AmqpsUrl      string                 `protobuf:"bytes,3,opt,name=amqps_url,json=amqpsUrl,proto3" json:"amqps_url,omitempty"`
	MgmtUrl       string                 `protobuf:"bytes,4,opt,name=mgmt_url,json=mgmtUrl,proto3" json:"mgmt_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionRabbitMQClusterResponse) Reset() {
	*x = ProvisionRabbitMQClusterResponse{}
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRabbitMQClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRabbitMQClusterResponse) ProtoMessage() {}

func (x *ProvisionRabbitMQClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRabbitMQClusterResponse.ProtoReflect.Descriptor instead.
func (*ProvisionRabbitMQClusterResponse) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_rabbitmq_proto_rawDescGZIP(), []int{3}
}

func (x *ProvisionRabbitMQClusterResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProvisionRabbitMQClusterResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ProvisionRabbitMQClusterResponse) GetAmqpsUrl() string {
	if x != nil {
		return x.AmqpsUrl
	}
	return ""
}

func (x *ProvisionRabbitMQClusterResponse) GetMgmtUrl() string {
	if x != nil {
		return x.MgmtUrl
	}
	return ""
}

type ListRabbitMQClustersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRabbitMQClustersRequest) Reset() {
	*x = ListRabbitMQClustersRequest{}
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRabbitMQClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRabbitMQClustersRequest) ProtoMessage() {}

func (x *ListRabbitMQClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRabbitMQClustersRequest.ProtoReflect.Descriptor instead.
func (*ListRabbitMQClustersRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_rabbitmq_proto_rawDescGZIP(), []int{4}
}

type ListRabbitMQClustersResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Clusters      []*RabbitMQClusterSummary `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRabbitMQClustersResponse) Reset() {
	*x = ListRabbitMQClustersResponse{}
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRabbitMQClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRabbitMQClustersResponse) ProtoMessage() {}

func (x *ListRabbitMQClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRabbitMQClustersResponse.ProtoReflect.Descriptor instead.
func (*ListRabbitMQClustersResponse) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_rabbitmq_proto_rawDescGZIP(), []int{5}
}

func (x *ListRabbitMQClustersResponse) GetClusters() []*RabbitMQClusterSummary {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type GetRabbitMQClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"required,max=40,hostname_rfc1123"` // @gotags: validate:"required,max=40,hostname_rfc1123"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRabbitMQClusterRequest) Reset() {
	*x = GetRabbitMQClusterRequest{}
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRabbitMQClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRabbitMQClusterRequest) ProtoMessage() {}

func (x *GetRabbitMQClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRabbitMQClusterRequest.ProtoReflect.Descriptor instead.
func (*GetRabbitMQClusterRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_rabbitmq_proto_rawDescGZIP(), []int{6}
}

func (x *GetRabbitMQClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRabbitMQClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *RabbitMQCluster       `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRabbitMQClusterResponse) Reset() {
	*x = GetRabbitMQClusterResponse{}
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRabbitMQClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRabbitMQClusterResponse) ProtoMessage() {}

func (x *GetRabbitMQClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRabbitMQClusterResponse.ProtoReflect.Descriptor instead.
func (*GetRabbitMQClusterResponse) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_rabbitmq_proto_rawDescGZIP(), []int{7}
}

func (x *GetRabbitMQClusterResponse) GetCluster() *RabbitMQCluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type DeleteRabbitMQClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"required,max=40,hostname_rfc1123"` // @gotags: validate:"required,max=40,hostname_rfc1123"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRabbitMQClusterRequest) Reset() {
	*x = DeleteRabbitMQClusterRequest{}
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRabbitMQClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRabbitMQClusterRequest) ProtoMessage() {}

func (x *DeleteRabbitMQClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRabbitMQClusterRequest.ProtoReflect.Descriptor instead.
func (*DeleteRabbitMQClusterRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_rabbitmq_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRabbitMQClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteRabbitMQClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRabbitMQClusterResponse) Reset() {
	*x = DeleteRabbitMQClusterResponse{}
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRabbitMQClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRabbitMQClusterResponse) ProtoMessage() {}

func (x *DeleteRabbitMQClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRabbitMQClusterResponse.ProtoReflect.Descriptor instead.
func (*DeleteRabbitMQClusterResponse) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_rabbitmq_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRabbitMQClusterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ExtendRabbitMQClusterLifeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"required,max=40,hostname_rfc1123"` // @gotags: validate:"required,max=40,hostname_rfc1123"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendRabbitMQClusterLifeRequest) Reset() {
	*x = ExtendRabbitMQClusterLifeRequest{}
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendRabbitMQClusterLifeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendRabbitMQClusterLifeRequest) ProtoMessage() {}

func (x *ExtendRabbitMQClusterLifeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendRabbitMQClusterLifeRequest.ProtoReflect.Descriptor instead.
func (*ExtendRabbitMQClusterLifeRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_rabbitmq_proto_rawDescGZIP(), []int{10}
}

func (x *ExtendRabbitMQClusterLifeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExtendRabbitMQClusterLifeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lifetime      *Lifetime              `protobuf:"bytes,1,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendRabbitMQClusterLifeResponse) Reset() {
	*x = ExtendRabbitMQClusterLifeResponse{}
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendRabbitMQClusterLifeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendRabbitMQClusterLifeResponse) ProtoMessage() {}

func (x *ExtendRabbitMQClusterLifeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendRabbitMQClusterLifeResponse.ProtoReflect.Descriptor instead.
func (*ExtendRabbitMQClusterLifeResponse) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_rabbitmq_proto_rawDescGZIP(), []int{11}
}

func (x *ExtendRabbitMQClusterLifeResponse) GetLifetime() *Lifetime {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

var File_proto_streaming_v1alpha_rabbitmq_proto protoreflect.FileDescriptor

const file_proto_streaming_v1alpha_rabbitmq_proto_rawDesc = "" +
	"\n" +
	"&proto/streaming/v1alpha/rabbitmq.proto\x12\x1aolcf.s3m.streaming.v1alpha\x1a$proto/streaming/v1alpha/common.proto\"\xc8\x01\n" +
	"\x16RabbitMQClusterSummary\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vsync_status\x18\x03 \x01(\tR\n" +
	"syncStatus\x12#\n" +
	"\rhealth_status\x18\x04 \x01(\tR\fhealthStatus\x12@\n" +
	"\blifetime\x18\x05 \x01(\v2$.olcf.s3m.streaming.v1alpha.LifetimeR\blifetime\"\xd4\x05\n" +
	"\x0fRabbitMQCluster\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vsync_status\x18\x03 \x01(\tR\n" +
	"syncStatus\x12#\n" +
	"\rhealth_status\x18\x04 \x01(\tR\fhealthStatus\x12@\n" +
	"\blifetime\x18\x05 \x01(\v2$.olcf.s3m.streaming.v1alpha.LifetimeR\blifetime\x12n\n" +
	"\x11resource_settings\x18\x06 \x03(\v2A.olcf.s3m.streaming.v1alpha.RabbitMQCluster.ResourceSettingsEntryR\x10resourceSettings\x12\x1f\n" +
	"\busername\x18\a \x01(\tH\x00R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\b \x01(\tH\x01R\bpassword\x88\x01\x01\x12 \n" +
	"\tamqps_url\x18\t \x01(\tH\x02R\bamqpsUrl\x88\x01\x01\x12\x1e\n" +
	"\bmgmt_url\x18\n" +
	" \x01(\tH\x03R\amgmtUrl\x88\x01\x01\x12b\n" +
	"\rfeature_flags\x18\v \x03(\v2=.olcf.s3m.streaming.v1alpha.RabbitMQCluster.FeatureFlagsEntryR\ffeatureFlags\x1aC\n" +
	"\x15ResourceSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a?\n" +
	"\x11FeatureFlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01B\v\n" +
	"\t_usernameB\v\n" +
	"\t_passwordB\f\n" +
	"\n" +
	"_amqps_urlB\v\n" +
	"\t_mgmt_url\"\xc3\x03\n" +
	"\x1fProvisionRabbitMQClusterRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12~\n" +
	"\x11resource_settings\x18\x03 \x03(\v2Q.olcf.s3m.streaming.v1alpha.ProvisionRabbitMQClusterRequest.ResourceSettingsEntryR\x10resourceSettings\x12r\n" +
	"\rfeature_flags\x18\x04 \x03(\v2M.olcf.s3m.streaming.v1alpha.ProvisionRabbitMQClusterRequest.FeatureFlagsEntryR\ffeatureFlags\x1aC\n" +
	"\x15ResourceSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a?\n" +
	"\x11FeatureFlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x92\x01\n" +
	" ProvisionRabbitMQClusterResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tamqps_url\x18\x03 \x01(\tR\bamqpsUrl\x12\x19\n" +
	"\bmgmt_url\x18\x04 \x01(\tR\amgmtUrl\"\x1d\n" +
	"\x1bListRabbitMQClustersRequest\"n\n" +
	"\x1cListRabbitMQClustersResponse\x12N\n" +
	"\bclusters\x18\x01 \x03(\v22.olcf.s3m.streaming.v1alpha.RabbitMQClusterSummaryR\bclusters\"/\n" +
	"\x19GetRabbitMQClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"c\n" +
	"\x1aGetRabbitMQClusterResponse\x12E\n" +
	"\acluster\x18\x01 \x01(\v2+.olcf.s3m.streaming.v1alpha.RabbitMQClusterR\acluster\"2\n" +
	"\x1cDeleteRabbitMQClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"9\n" +
	"\x1dDeleteRabbitMQClusterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"6\n" +
	" ExtendRabbitMQClusterLifeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"e\n" +
	"!ExtendRabbitMQClusterLifeResponse\x12@\n" +
	"\blifetime\x18\x01 \x01(\v2$.olcf.s3m.streaming.v1alpha.LifetimeR\blifetimeB8Z6github.com/olcf/s3m-apis/streaming/v1alpha;streamingpbb\x06proto3"

var (
	file_proto_streaming_v1alpha_rabbitmq_proto_rawDescOnce sync.Once
	file_proto_streaming_v1alpha_rabbitmq_proto_rawDescData []byte
)

func file_proto_streaming_v1alpha_rabbitmq_proto_rawDescGZIP() []byte {
	file_proto_streaming_v1alpha_rabbitmq_proto_rawDescOnce.Do(func() {
		file_proto_streaming_v1alpha_rabbitmq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_streaming_v1alpha_rabbitmq_proto_rawDesc), len(file_proto_streaming_v1alpha_rabbitmq_proto_rawDesc)))
	})
	return file_proto_streaming_v1alpha_rabbitmq_proto_rawDescData
}

var file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_streaming_v1alpha_rabbitmq_proto_goTypes = []any{
	(*RabbitMQClusterSummary)(nil),            // 0: olcf.s3m.streaming.v1alpha.RabbitMQClusterSummary
	(*RabbitMQCluster)(nil),                   // 1: olcf.s3m.streaming.v1alpha.RabbitMQCluster
	(*ProvisionRabbitMQClusterRequest)(nil),   // 2: olcf.s3m.streaming.v1alpha.ProvisionRabbitMQClusterRequest
	(*ProvisionRabbitMQClusterResponse)(nil),  // 3: olcf.s3m.streaming.v1alpha.ProvisionRabbitMQClusterResponse
	(*ListRabbitMQClustersRequest)(nil),       // 4: olcf.s3m.streaming.v1alpha.ListRabbitMQClustersRequest
	(*ListRabbitMQClustersResponse)(nil),      // 5: olcf.s3m.streaming.v1alpha.ListRabbitMQClustersResponse
	(*GetRabbitMQClusterRequest)(nil),         // 6: olcf.s3m.streaming.v1alpha.GetRabbitMQClusterRequest
	(*GetRabbitMQClusterResponse)(nil),        // 7: olcf.s3m.streaming.v1alpha.GetRabbitMQClusterResponse
	(*DeleteRabbitMQClusterRequest)(nil),      // 8: olcf.s3m.streaming.v1alpha.DeleteRabbitMQClusterRequest
	(*DeleteRabbitMQClusterResponse)(nil),     // 9: olcf.s3m.streaming.v1alpha.DeleteRabbitMQClusterResponse
	(*ExtendRabbitMQClusterLifeRequest)(nil),  // 10: olcf.s3m.streaming.v1alpha.ExtendRabbitMQClusterLifeRequest
	(*ExtendRabbitMQClusterLifeResponse)(nil), // 11: olcf.s3m.streaming.v1alpha.ExtendRabbitMQClusterLifeResponse
	nil,              // 12: olcf.s3m.streaming.v1alpha.RabbitMQCluster.ResourceSettingsEntry
	nil,              // 13: olcf.s3m.streaming.v1alpha.RabbitMQCluster.FeatureFlagsEntry
	nil,              // 14: olcf.s3m.streaming.v1alpha.ProvisionRabbitMQClusterRequest.ResourceSettingsEntry
	nil,              // 15: olcf.s3m.streaming.v1alpha.ProvisionRabbitMQClusterRequest.FeatureFlagsEntry
	(*Lifetime)(nil), // 16: olcf.s3m.streaming.v1alpha.Lifetime
}
var file_proto_streaming_v1alpha_rabbitmq_proto_depIdxs = []int32{
	16, // 0: olcf.s3m.streaming.v1alpha.RabbitMQClusterSummary.lifetime:type_name -> olcf.s3m.streaming.v1alpha.Lifetime
	16, // 1: olcf.s3m.streaming.v1alpha.RabbitMQCluster.lifetime:type_name -> olcf.s3m.streaming.v1alpha.Lifetime
	12, // 2: olcf.s3m.streaming.v1alpha.RabbitMQCluster.resource_settings:type_name -> olcf.s3m.streaming.v1alpha.RabbitMQCluster.ResourceSettingsEntry
	13, // 3: olcf.s3m.streaming.v1alpha.RabbitMQCluster.feature_flags:type_name -> olcf.s3m.streaming.v1alpha.RabbitMQCluster.FeatureFlagsEntry
	14, // 4: olcf.s3m.streaming.v1alpha.ProvisionRabbitMQClusterRequest.resource_settings:type_name -> olcf.s3m.streaming.v1alpha.ProvisionRabbitMQClusterRequest.ResourceSettingsEntry
	15, // 5: olcf.s3m.streaming.v1alpha.ProvisionRabbitMQClusterRequest.feature_flags:type_name -> olcf.s3m.streaming.v1alpha.ProvisionRabbitMQClusterRequest.FeatureFlagsEntry
	0,  // 6: olcf.s3m.streaming.v1alpha.ListRabbitMQClustersResponse.clusters:type_name -> olcf.s3m.streaming.v1alpha.RabbitMQClusterSummary
	1,  // 7: olcf.s3m.streaming.v1alpha.GetRabbitMQClusterResponse.cluster:type_name -> olcf.s3m.streaming.v1alpha.RabbitMQCluster
	16, // 8: olcf.s3m.streaming.v1alpha.ExtendRabbitMQClusterLifeResponse.lifetime:type_name -> olcf.s3m.streaming.v1alpha.Lifetime
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_streaming_v1alpha_rabbitmq_proto_init() }
func file_proto_streaming_v1alpha_rabbitmq_proto_init() {
	if File_proto_streaming_v1alpha_rabbitmq_proto != nil {
		return
	}
	file_proto_streaming_v1alpha_common_proto_init()
	file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_streaming_v1alpha_rabbitmq_proto_rawDesc), len(file_proto_streaming_v1alpha_rabbitmq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_streaming_v1alpha_rabbitmq_proto_goTypes,
		DependencyIndexes: file_proto_streaming_v1alpha_rabbitmq_proto_depIdxs,
		MessageInfos:      file_proto_streaming_v1alpha_rabbitmq_proto_msgTypes,
	}.Build()
	File_proto_streaming_v1alpha_rabbitmq_proto = out.File
	file_proto_streaming_v1alpha_rabbitmq_proto_goTypes = nil
	file_proto_streaming_v1alpha_rabbitmq_proto_depIdxs = nil
}
