// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/streaming/v1alpha/redis.proto

package streamingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedisClusterSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SyncStatus    string                 `protobuf:"bytes,3,opt,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty"`
	HealthStatus  string                 `protobuf:"bytes,4,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	Lifetime      *Lifetime              `protobuf:"bytes,5,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisClusterSummary) Reset() {
	*x = RedisClusterSummary{}
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisClusterSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisClusterSummary) ProtoMessage() {}

func (x *RedisClusterSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisClusterSummary.ProtoReflect.Descriptor instead.
func (*RedisClusterSummary) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_redis_proto_rawDescGZIP(), []int{0}
}

func (x *RedisClusterSummary) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RedisClusterSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RedisClusterSummary) GetSyncStatus() string {
	if x != nil {
		return x.SyncStatus
	}
	return ""
}

func (x *RedisClusterSummary) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

func (x *RedisClusterSummary) GetLifetime() *Lifetime {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

type RedisCluster struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Kind             string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SyncStatus       string                 `protobuf:"bytes,3,opt,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty"`
	HealthStatus     string                 `protobuf:"bytes,4,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	Lifetime         *Lifetime              `protobuf:"bytes,5,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	ResourceSettings map[string]int32       `protobuf:"bytes,6,rep,name=resource_settings,json=resourceSettings,proto3" json:"resource_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Username         *string                `protobuf:"bytes,7,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password         *string                `protobuf:"bytes,8,opt,name=password,proto3,oneof" json:"password,omitempty"`
	RedisUrl         *string                `protobuf:"bytes,9,opt,name=redis_url,json=redisUrl,proto3,oneof" json:"redis_url,omitempty"`
	FeatureFlags     map[string]bool        `protobuf:"bytes,10,rep,name=feature_flags,json=featureFlags,proto3" json:"feature_flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RedisCluster) Reset() {
	*x = RedisCluster{}
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisCluster) ProtoMessage() {}

func (x *RedisCluster) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisCluster.ProtoReflect.Descriptor instead.
func (*RedisCluster) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_redis_proto_rawDescGZIP(), []int{1}
}

func (x *RedisCluster) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RedisCluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RedisCluster) GetSyncStatus() string {
	if x != nil {
		return x.SyncStatus
	}
	return ""
}

func (x *RedisCluster) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

func (x *RedisCluster) GetLifetime() *Lifetime {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *RedisCluster) GetResourceSettings() map[string]int32 {
	if x != nil {
		return x.ResourceSettings
	}
	return nil
}

func (x *RedisCluster) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *RedisCluster) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *RedisCluster) GetRedisUrl() string {
	if x != nil && x.RedisUrl != nil {
		return *x.RedisUrl
	}
	return ""
}

func (x *RedisCluster) GetFeatureFlags() map[string]bool {
	if x != nil {
		return x.FeatureFlags
	}
	return nil
}

type ProvisionRedisClusterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Kind             string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" validate:"required"`                                                                                                                            // @gotags: validate:"required"
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" validate:"required,max=40,hostname_rfc1123"`                                                                                                                            // @gotags: validate:"required,max=40,hostname_rfc1123"
	ResourceSettings map[string]int32       `protobuf:"bytes,3,rep,name=resource_settings,json=resourceSettings,proto3" json:"resource_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value" validate:"dive,keys,endkeys,gt=0"` // @gotags: validate:"dive,keys,endkeys,gt=0"
	FeatureFlags     map[string]bool        `protobuf:"bytes,4,rep,name=feature_flags,json=featureFlags,proto3" json:"feature_flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProvisionRedisClusterRequest) Reset() {
	*x = ProvisionRedisClusterRequest{}
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRedisClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRedisClusterRequest) ProtoMessage() {}

func (x *ProvisionRedisClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRedisClusterRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRedisClusterRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_redis_proto_rawDescGZIP(), []int{2}
}

func (x *ProvisionRedisClusterRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProvisionRedisClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProvisionRedisClusterRequest) GetResourceSettings() map[string]int32 {
	if x != nil {
		return x.ResourceSettings
	}
	return nil
}

func (x *ProvisionRedisClusterRequest) GetFeatureFlags() map[string]bool {
	if x != nil {
		return x.FeatureFlags
	}
	return nil
}

type ProvisionRedisClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionRedisClusterResponse) Reset() {
	*x = ProvisionRedisClusterResponse{}
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRedisClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRedisClusterResponse) ProtoMessage() {}

func (x *ProvisionRedisClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRedisClusterResponse.ProtoReflect.Descriptor instead.
func (*ProvisionRedisClusterResponse) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_redis_proto_rawDescGZIP(), []int{3}
}

func (x *ProvisionRedisClusterResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProvisionRedisClusterResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ProvisionRedisClusterResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListRedisClustersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRedisClustersRequest) Reset() {
	*x = ListRedisClustersRequest{}
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRedisClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRedisClustersRequest) ProtoMessage() {}

func (x *ListRedisClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRedisClustersRequest.ProtoReflect.Descriptor instead.
func (*ListRedisClustersRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_redis_proto_rawDescGZIP(), []int{4}
}

type ListRedisClustersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*RedisClusterSummary `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRedisClustersResponse) Reset() {
	*x = ListRedisClustersResponse{}
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRedisClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRedisClustersResponse) ProtoMessage() {}

func (x *ListRedisClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRedisClustersResponse.ProtoReflect.Descriptor instead.
func (*ListRedisClustersResponse) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_redis_proto_rawDescGZIP(), []int{5}
}

func (x *ListRedisClustersResponse) GetClusters() []*RedisClusterSummary {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type GetRedisClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"required,max=40,hostname_rfc1123"` // @gotags: validate:"required,max=40,hostname_rfc1123"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedisClusterRequest) Reset() {
	*x = GetRedisClusterRequest{}
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedisClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedisClusterRequest) ProtoMessage() {}

func (x *GetRedisClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedisClusterRequest.ProtoReflect.Descriptor instead.
func (*GetRedisClusterRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_redis_proto_rawDescGZIP(), []int{6}
}

func (x *GetRedisClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRedisClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *RedisCluster          `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedisClusterResponse) Reset() {
	*x = GetRedisClusterResponse{}
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedisClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedisClusterResponse) ProtoMessage() {}

func (x *GetRedisClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedisClusterResponse.ProtoReflect.Descriptor instead.
func (*GetRedisClusterResponse) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_redis_proto_rawDescGZIP(), []int{7}
}

func (x *GetRedisClusterResponse) GetCluster() *RedisCluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type DeleteRedisClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"required,max=40,hostname_rfc1123"` // @gotags: validate:"required,max=40,hostname_rfc1123"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRedisClusterRequest) Reset() {
	*x = DeleteRedisClusterRequest{}
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRedisClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRedisClusterRequest) ProtoMessage() {}

func (x *DeleteRedisClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRedisClusterRequest.ProtoReflect.Descriptor instead.
func (*DeleteRedisClusterRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_redis_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRedisClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteRedisClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRedisClusterResponse) Reset() {
	*x = DeleteRedisClusterResponse{}
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRedisClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRedisClusterResponse) ProtoMessage() {}

func (x *DeleteRedisClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRedisClusterResponse.ProtoReflect.Descriptor instead.
func (*DeleteRedisClusterResponse) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_redis_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRedisClusterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ExtendRedisClusterLifeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"required,max=40,hostname_rfc1123"` // @gotags: validate:"required,max=40,hostname_rfc1123"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendRedisClusterLifeRequest) Reset() {
	*x = ExtendRedisClusterLifeRequest{}
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendRedisClusterLifeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendRedisClusterLifeRequest) ProtoMessage() {}

func (x *ExtendRedisClusterLifeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendRedisClusterLifeRequest.ProtoReflect.Descriptor instead.
func (*ExtendRedisClusterLifeRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_redis_proto_rawDescGZIP(), []int{10}
}

func (x *ExtendRedisClusterLifeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExtendRedisClusterLifeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lifetime      *Lifetime              `protobuf:"bytes,1,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendRedisClusterLifeResponse) Reset() {
	*x = ExtendRedisClusterLifeResponse{}
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendRedisClusterLifeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendRedisClusterLifeResponse) ProtoMessage() {}

func (x *ExtendRedisClusterLifeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_v1alpha_redis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendRedisClusterLifeResponse.ProtoReflect.Descriptor instead.
func (*ExtendRedisClusterLifeResponse) Descriptor() ([]byte, []int) {
	return file_proto_streaming_v1alpha_redis_proto_rawDescGZIP(), []int{11}
}

func (x *ExtendRedisClusterLifeResponse) GetLifetime() *Lifetime {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

var File_proto_streaming_v1alpha_redis_proto protoreflect.FileDescriptor

const file_proto_streaming_v1alpha_redis_proto_rawDesc = "" +
	"\n" +
	"#proto/streaming/v1alpha/redis.proto\x12\x1aolcf.s3m.streaming.v1alpha\x1a$proto/streaming/v1alpha/common.proto\"\xc5\x01\n" +
	"\x13RedisClusterSummary\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vsync_status\x18\x03 \x01(\tR\n" +
	"syncStatus\x12#\n" +
	"\rhealth_status\x18\x04 \x01(\tR\fhealthStatus\x12@\n" +
	"\blifetime\x18\x05 \x01(\v2$.olcf.s3m.streaming.v1alpha.LifetimeR\blifetime\"\x9e\x05\n" +
	"\fRedisCluster\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vsync_status\x18\x03 \x01(\tR\n" +
	"syncStatus\x12#\n" +
	"\rhealth_status\x18\x04 \x01(\tR\fhealthStatus\x12@\n" +
	"\blifetime\x18\x05 \x01(\v2$.olcf.s3m.streaming.v1alpha.LifetimeR\blifetime\x12k\n" +
	"\x11resource_settings\x18\x06 \x03(\v2>.olcf.s3m.streaming.v1alpha.RedisCluster.ResourceSettingsEntryR\x10resourceSettings\x12\x1f\n" +
	"\busername\x18\a \x01(\tH\x00R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\b \x01(\tH\x01R\bpassword\x88\x01\x01\x12 \n" +
	"\tredis_url\x18\t \x01(\tH\x02R\bredisUrl\x88\x01\x01\x12_\n" +
	"\rfeature_flags\x18\n" +
	" \x03(\v2:.olcf.s3m.streaming.v1alpha.RedisCluster.FeatureFlagsEntryR\ffeatureFlags\x1aC\n" +
	"\x15ResourceSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a?\n" +
	"\x11FeatureFlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01B\v\n" +
	"\t_usernameB\v\n" +
	"\t_passwordB\f\n" +
	"\n" +
	"_redis_url\"\xba\x03\n" +
	"\x1cProvisionRedisClusterRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12{\n" +
	"\x11resource_settings\x18\x03 \x03(\v2N.olcf.s3m.streaming.v1alpha.ProvisionRedisClusterRequest.ResourceSettingsEntryR\x10resourceSettings\x12o\n" +
	"\rfeature_flags\x18\x04 \x03(\v2J.olcf.s3m.streaming.v1alpha.ProvisionRedisClusterRequest.FeatureFlagsEntryR\ffeatureFlags\x1aC\n" +
	"\x15ResourceSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a?\n" +
	"\x11FeatureFlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"i\n" +
	"\x1dProvisionRedisClusterResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x1a\n" +
	"\x18ListRedisClustersRequest\"h\n" +
	"\x19ListRedisClustersResponse\x12K\n" +
	"\bclusters\x18\x01 \x03(\v2/.olcf.s3m.streaming.v1alpha.RedisClusterSummaryR\bclusters\",\n" +
	"\x16GetRedisClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"]\n" +
	"\x17GetRedisClusterResponse\x12B\n" +
	"\acluster\x18\x01 \x01(\v2(.olcf.s3m.streaming.v1alpha.RedisClusterR\acluster\"/\n" +
	"\x19DeleteRedisClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"6\n" +
	"\x1aDeleteRedisClusterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x1dExtendRedisClusterLifeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"b\n" +
	"\x1eExtendRedisClusterLifeResponse\x12@\n" +
	"\blifetime\x18\x01 \x01(\v2$.olcf.s3m.streaming.v1alpha.LifetimeR\blifetimeB8Z6github.com/olcf/s3m-apis/streaming/v1alpha;streamingpbb\x06proto3"

var (
	file_proto_streaming_v1alpha_redis_proto_rawDescOnce sync.Once
	file_proto_streaming_v1alpha_redis_proto_rawDescData []byte
)

func file_proto_streaming_v1alpha_redis_proto_rawDescGZIP() []byte {
	file_proto_streaming_v1alpha_redis_proto_rawDescOnce.Do(func() {
		file_proto_streaming_v1alpha_redis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_streaming_v1alpha_redis_proto_rawDesc), len(file_proto_streaming_v1alpha_redis_proto_rawDesc)))
	})
	return file_proto_streaming_v1alpha_redis_proto_rawDescData
}

var file_proto_streaming_v1alpha_redis_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_streaming_v1alpha_redis_proto_goTypes = []any{
	(*RedisClusterSummary)(nil),            // 0: olcf.s3m.streaming.v1alpha.RedisClusterSummary
	(*RedisCluster)(nil),                   // 1: olcf.s3m.streaming.v1alpha.RedisCluster
	(*ProvisionRedisClusterRequest)(nil),   // 2: olcf.s3m.streaming.v1alpha.ProvisionRedisClusterRequest
	(*ProvisionRedisClusterResponse)(nil),  // 3: olcf.s3m.streaming.v1alpha.ProvisionRedisClusterResponse
	(*ListRedisClustersRequest)(nil),       // 4: olcf.s3m.streaming.v1alpha.ListRedisClustersRequest
	(*ListRedisClustersResponse)(nil),      // 5: olcf.s3m.streaming.v1alpha.ListRedisClustersResponse
	(*GetRedisClusterRequest)(nil),         // 6: olcf.s3m.streaming.v1alpha.GetRedisClusterRequest
	(*GetRedisClusterResponse)(nil),        // 7: olcf.s3m.streaming.v1alpha.GetRedisClusterResponse
	(*DeleteRedisClusterRequest)(nil),      // 8: olcf.s3m.streaming.v1alpha.DeleteRedisClusterRequest
	(*DeleteRedisClusterResponse)(nil),     // 9: olcf.s3m.streaming.v1alpha.DeleteRedisClusterResponse
	(*ExtendRedisClusterLifeRequest)(nil),  // 10: olcf.s3m.streaming.v1alpha.ExtendRedisClusterLifeRequest
	(*ExtendRedisClusterLifeResponse)(nil), // 11: olcf.s3m.streaming.v1alpha.ExtendRedisClusterLifeResponse
	nil,                                    // 12: olcf.s3m.streaming.v1alpha.RedisCluster.ResourceSettingsEntry
	nil,                                    // 13: olcf.s3m.streaming.v1alpha.RedisCluster.FeatureFlagsEntry
	nil,                                    // 14: olcf.s3m.streaming.v1alpha.ProvisionRedisClusterRequest.ResourceSettingsEntry
	nil,                                    // 15: olcf.s3m.streaming.v1alpha.ProvisionRedisClusterRequest.FeatureFlagsEntry
	(*Lifetime)(nil),                       // 16: olcf.s3m.streaming.v1alpha.Lifetime
}
var file_proto_streaming_v1alpha_redis_proto_depIdxs = []int32{
	16, // 0: olcf.s3m.streaming.v1alpha.RedisClusterSummary.lifetime:type_name -> olcf.s3m.streaming.v1alpha.Lifetime
	16, // 1: olcf.s3m.streaming.v1alpha.RedisCluster.lifetime:type_name -> olcf.s3m.streaming.v1alpha.Lifetime
	12, // 2: olcf.s3m.streaming.v1alpha.RedisCluster.resource_settings:type_name -> olcf.s3m.streaming.v1alpha.RedisCluster.ResourceSettingsEntry
	13, // 3: olcf.s3m.streaming.v1alpha.RedisCluster.feature_flags:type_name -> olcf.s3m.streaming.v1alpha.RedisCluster.FeatureFlagsEntry
	14, // 4: olcf.s3m.streaming.v1alpha.ProvisionRedisClusterRequest.resource_settings:type_name -> olcf.s3m.streaming.v1alpha.ProvisionRedisClusterRequest.ResourceSettingsEntry
	15, // 5: olcf.s3m.streaming.v1alpha.ProvisionRedisClusterRequest.feature_flags:type_name -> olcf.s3m.streaming.v1alpha.ProvisionRedisClusterRequest.FeatureFlagsEntry
	0,  // 6: olcf.s3m.streaming.v1alpha.ListRedisClustersResponse.clusters:type_name -> olcf.s3m.streaming.v1alpha.RedisClusterSummary
	1,  // 7: olcf.s3m.streaming.v1alpha.GetRedisClusterResponse.cluster:type_name -> olcf.s3m.streaming.v1alpha.RedisCluster
	16, // 8: olcf.s3m.streaming.v1alpha.ExtendRedisClusterLifeResponse.lifetime:type_name -> olcf.s3m.streaming.v1alpha.Lifetime
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_streaming_v1alpha_redis_proto_init() }
func file_proto_streaming_v1alpha_redis_proto_init() {
	if File_proto_streaming_v1alpha_redis_proto != nil {
		return
	}
	file_proto_streaming_v1alpha_common_proto_init()
	file_proto_streaming_v1alpha_redis_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_streaming_v1alpha_redis_proto_rawDesc), len(file_proto_streaming_v1alpha_redis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_streaming_v1alpha_redis_proto_goTypes,
		DependencyIndexes: file_proto_streaming_v1alpha_redis_proto_depIdxs,
		MessageInfos:      file_proto_streaming_v1alpha_redis_proto_msgTypes,
	}.Build()
	File_proto_streaming_v1alpha_redis_proto = out.File
	file_proto_streaming_v1alpha_redis_proto_goTypes = nil
	file_proto_streaming_v1alpha_redis_proto_depIdxs = nil
}
